# Generated by Django 5.2 on 2025-05-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=100)),
                ('num_hab', models.CharField(max_length=10, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('reservada', models.BooleanField(default=False)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='reservas.lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.habitacion')),
            ],
            options={
                'unique_together': {('habitacion', 'fecha_inicio', 'fecha_fin')},
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='habitaciones_reservadas',
            field=models.ManyToManyField(blank=True, related_name='clientes', through='reservas.Reserva', to='reservas.habitacion'),
        ),
    ]
