# Generated by Django 5.2 on 2025-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_lugar_habitacion_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lugar',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
