# Generated by Django 5.2 on 2025-06-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='lugar',
        ),
        migrations.AddField(
            model_name='lugar',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='reservas.ciudad'),
        ),
    ]
